version: "3"

services:

  client:
    build: ./client
    image: client
    container_name: hs-client
    volumes:
      - ./client:/usr/src/client
    ports:
      - "3001:3001"
    networks:
      - hs-network
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: hs-mongo
    ports:
      - "27017:27017"
    networks:
      - hs-network
    volumes:
      - mongo-data:/data/db

networks:
  hs-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
