const errorCodes = {
	LOGIN_INCORRECT_CREDENTIALS: 'LOGIN_INCORRECT_CREDENTIALS',
	LOGIN_INCORRECT_PASSWORD_CONFIRMATION: 'LOGIN_INCORRECT_PASSWORD_CONFIRMATION',
	REGISTER_EMAIL_EXISTS_ERROR: 'REGISTER_EMAIL_EXISTS_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
};

export default errorCodes;
